### ISSUE TITLE
Als User möchte ich Icons sehen, die bei großen Bildschirmen nicht pixelig aussehen

### ISSUE THREAD

**Issue by DavidBlaa** [DavidBlaa/kukuwi#12]
> Hier muss nach einem passenden Icon set gesucht werden.

## Akzeptanzkriterien
- [x] Das Icon set Anzahl an akustischen Instrumenten
- [x] #23

**Comment by DavidBlaa** [comment]
https://www.autodraw.com/

**Comment by sventhiel** [comment]
Austausch der Icons mit denen, die David zur Verfügung gestellt hat.
